<?php

namespace Database\Seeders;

use App\Models\TranslationPassage;
use Illuminate\Database\Seeder;

// Seed đoạn văn luyện dịch EN->VI, 5 đoạn/cấp độ (A1-C1) để mỗi lần vào bài random ra đoạn khác nhau (mục 5)
class TranslationPassageSeeder extends Seeder
{
    public function run(): void
    {
        $passages = [
            'A1' => [
                "My name is Linh. I am twelve years old. I live with my mother, my father, and my little brother. My mother is a teacher. My father works in a shop. Every morning, I go to school by bike. I have four classes in the morning and two classes in the afternoon. My favorite subject is English. After school, I do my homework and play with my brother. In the evening, we eat dinner together. I love my family very much.",
                "This is my house. It is small but very nice. There are three rooms: a bedroom, a kitchen, and a living room. My bedroom has a bed, a table, and a chair. I have many books on my table. The kitchen is next to the living room. We watch television in the living room every night. There is a small garden behind the house. My mother grows flowers there. I like to help her water the flowers on Sunday morning.",
                "Every day, I wake up at six o'clock. First, I brush my teeth and wash my face. Then I eat breakfast with my family. I usually have bread and milk. After breakfast, I go to school. School starts at seven thirty. I study Math, English, and Science. At twelve o'clock, I have lunch at school. School finishes at four. When I come home, I do my homework. I go to bed at nine thirty.",
                "My favorite food is chicken rice. My mother cooks it every Sunday. She uses chicken, rice, and vegetables. It smells very good. I also like fruit. My favorite fruit is mango. It is sweet and yellow. In the summer, I eat mango every day. My brother likes ice cream more than fruit. He eats ice cream after lunch. We do not eat fast food very often because our mother thinks it is not healthy.",
                "My school is not big, but it is very nice. There are twenty classrooms and a big playground. I am in class 6A. There are thirty students in my class. My teacher is Miss Hoa. She is kind and helpful. We study many subjects: Math, English, Science, and Art. I like Art class because I can draw pictures. At break time, we play games with our friends in the playground. I am happy at school.",
            ],
            'A2' => [
                "Last summer, my family went on holiday to Da Lat. We stayed there for five days. The weather was cool and nice, so different from the hot weather in our city. We visited a beautiful lake and walked around a flower garden. My favorite part was the market at night. We tried many kinds of local food, like grilled corn and strawberry ice cream. My little sister bought some souvenirs for her friends. On the last day, we visited a coffee farm and learned how coffee is made. It was a wonderful trip, and I hope we can go there again next year.",
                "This weekend, I have a lot of plans. On Saturday morning, I am going to play football with my friends in the park. In the afternoon, I need to go shopping with my mother because my cousin's birthday party is on Sunday. We plan to buy a nice present for him. In the evening, I will study for my English test on Monday. On Sunday, after the birthday party, I want to relax at home and watch a movie with my family. I hope the weather will be good this weekend.",
                "Yesterday, I went shopping with my friend at a big supermarket near my house. We wanted to buy some clothes for the new school year. First, we looked at shirts and trousers. I found a nice blue shirt, but it was too expensive, so I chose a cheaper one instead. My friend bought a pair of shoes. After shopping, we were hungry, so we had lunch at a small restaurant. We ordered noodles and fresh juice. It was a fun afternoon, and I am happy with the things I bought.",
                "Last week, I did not feel well, so my mother took me to see a doctor. I had a headache and a small fever. The doctor asked me some questions and checked my temperature. She said it was just a small cold and told me to rest and drink a lot of water. She also gave me some medicine to take twice a day. I stayed at home for two days and did not go to school. Now I feel much better, and I can go back to school tomorrow.",
                "I was born in a small town near the sea. It is a quiet and peaceful place. Most people there work as fishermen or farmers. There are not many tall buildings, but there are many trees and green fields. My favorite place in my hometown is the beach. When I was young, I often went there with my friends after school. We played games and watched the sunset together. Although I now live in a big city for my studies, I always miss my hometown, especially during holidays.",
            ],
            'B1' => [
                "It is always interesting to learn about different cultures and their traditions. For example, the way people greet each other can be very different. In my country, it is common to shake hands when you meet someone for the first time. But in Japan, people often bow. Food is another big part of culture. Every country has its own special dishes. In Italy, pasta is very popular. In India, people eat a lot of curry. Festivals are also an important part of culture. They are a time for people to celebrate their history and traditions together. For example, Chinese New Year is a very big festival in China and other parts of Asia. Learning about other cultures helps us to be more open-minded and understanding. It shows us that there are many different ways to live. I hope to travel a lot in the future to experience these different cultures myself.",
                "Technology has changed the way we live in many ways. Twenty years ago, few people had smartphones or used the internet every day. Now, most people cannot imagine life without them. We use technology to communicate with friends and family, to study, to work, and even to shop for food. Social media allows us to stay connected with people all over the world. However, technology also brings some problems. Some people spend too much time on their phones and forget to talk with the people around them. Others worry that children today do not play outside as much as before because they prefer watching videos or playing games on screens. I believe that technology is very useful, but we need to use it in a balanced way so that it does not control our lives.",
                "Environmental problems are becoming more serious around the world. Air pollution in big cities is making it harder for people to breathe clean air. Plastic waste is filling our oceans and harming sea animals. Forests are being cut down to make space for farms and buildings, which affects the homes of many wild animals. These problems are caused by both companies and individuals, so everyone has a role to play in solving them. Governments can create stronger laws to protect the environment. Companies can use less plastic and more recycled materials. As individuals, we can also help by using public transport, saving electricity, and recycling waste at home. If we all work together, we can slow down these problems and protect our planet for future generations.",
                "Learning a new language is not easy, but it brings many benefits. First, it opens the door to new job opportunities, especially in a world where many companies work with international partners. Second, it allows you to understand a different culture more deeply, because language and culture are closely connected. Third, studying a language can improve your memory and thinking skills. There are many ways to learn a new language today. You can take classes, watch movies, listen to music, or use mobile apps. Some people also like to find a language partner to practice speaking with. The most important thing is to practice regularly and not be afraid of making mistakes. Mistakes are a natural part of learning, and they help us improve over time.",
                "Having a healthy lifestyle is important for both our body and our mind. Eating a balanced diet with enough fruits and vegetables gives our body the energy and nutrients it needs. Regular exercise, such as walking, swimming, or playing sports, helps keep our heart and muscles strong. It is also important to get enough sleep every night, because our body needs time to rest and recover. Besides physical health, mental health is equally important. Spending time with friends and family, doing hobbies we enjoy, and taking breaks from work can help reduce stress. Many people today live busy lives and forget to take care of themselves. However, making small changes, like going for a short walk or cooking a healthy meal, can make a big difference over time.",
            ],
            'B2' => [
                "Social media has transformed the way people communicate, share information, and form opinions. On one hand, it has made it easier than ever to stay in touch with friends and family, regardless of distance, and it has given ordinary people a platform to express their views on important issues. Small businesses have also benefited greatly, as social media allows them to reach customers without spending large amounts of money on advertising. On the other hand, there are growing concerns about its negative effects. Studies suggest that excessive use of social media can contribute to anxiety and low self-esteem, particularly among young people who compare their lives to the carefully edited posts of others. Misinformation also spreads quickly on these platforms, sometimes with serious consequences. As social media continues to play a larger role in our daily lives, it is essential that both individuals and society find ways to use it responsibly.",
                "Education systems vary greatly from one country to another, reflecting different cultural values and priorities. In some countries, the education system places a strong emphasis on memorization and standardized testing, with students expected to spend long hours studying to achieve high scores. Critics argue that this approach can create excessive pressure and does not necessarily encourage creativity or critical thinking. In contrast, other education systems focus more on practical skills, group projects, and independent thinking, allowing students greater freedom to explore subjects that interest them. Neither approach is perfect, and each has its own strengths and weaknesses. As the global economy continues to change rapidly, many education experts believe that schools should aim to combine strong academic knowledge with skills such as problem-solving, communication, and adaptability, in order to better prepare students for the challenges of the future.",
                "Achieving a healthy work-life balance has become increasingly difficult in modern society, especially with the rise of remote work and constant connectivity through smartphones and email. Many employees report feeling pressure to respond to work messages outside of office hours, which blurs the line between personal and professional life. This constant availability can lead to burnout, reduced productivity, and negative effects on both physical and mental health. Some companies have started to address this issue by introducing policies such as flexible working hours, limits on after-hours communication, and additional paid leave. However, achieving a genuine balance also requires individuals to set their own boundaries and prioritize activities outside of work, such as spending time with family, exercising, or pursuing hobbies. Ultimately, both employers and employees share responsibility for creating a sustainable and healthy approach to work.",
                "Renewable energy sources, such as solar, wind, and hydroelectric power, are increasingly seen as essential solutions to the problem of climate change. Unlike fossil fuels, which release large amounts of carbon dioxide when burned, renewable sources produce little to no direct emissions, making them a cleaner alternative for generating electricity. In recent years, the cost of renewable technology, particularly solar panels, has dropped significantly, making it more accessible to both households and businesses. Despite these advantages, the transition to renewable energy still faces several challenges. Some renewable sources depend heavily on weather conditions, which can make electricity supply less predictable. Additionally, large-scale investment in new infrastructure, such as power grids and storage systems, is required to fully replace traditional energy sources. Nevertheless, many governments and organizations continue to invest heavily in renewable energy, recognizing its long-term benefits for both the environment and the economy.",
                "Urbanization, the process by which an increasing proportion of a population comes to live in cities, has accelerated rapidly over the past century. Cities offer numerous advantages, including greater access to job opportunities, education, healthcare, and cultural activities, which continue to attract people from rural areas. However, rapid urban growth also brings significant challenges. Overcrowding can lead to housing shortages and rising property prices, making it difficult for lower-income residents to find affordable homes. Traffic congestion and air pollution are also common problems in many large cities, affecting both the environment and public health. To address these issues, urban planners are increasingly focused on developing sustainable cities that incorporate green spaces, efficient public transportation, and affordable housing. Successfully managing urbanization will be crucial for ensuring that cities remain livable and continue to provide opportunities for their growing populations.",
            ],
            'C1' => [
                "The rapid advancement of artificial intelligence has sparked intense debate about its ethical implications, particularly as these systems become increasingly integrated into decision-making processes that affect people's lives. Proponents argue that AI can improve efficiency and reduce human bias in areas such as hiring, lending, and medical diagnosis, since algorithms are not subject to fatigue or personal prejudice in the same way humans are. Critics, however, point out that AI systems are only as unbiased as the data on which they are trained, and that historical inequalities embedded in that data can be inadvertently perpetuated or even amplified. Furthermore, the lack of transparency in many AI systems, often referred to as the 'black box' problem, raises concerns about accountability when decisions cannot be easily explained or challenged. As policymakers grapple with how to regulate this rapidly evolving technology, a central challenge will be striking a balance between fostering innovation and safeguarding fundamental rights.",
                "Economic inequality has emerged as one of the defining issues of the twenty-first century, with the gap between the wealthiest and poorest segments of society widening in many countries despite overall economic growth. Economists attribute this trend to a variety of factors, including technological change that has disproportionately rewarded highly skilled workers, the decline of labor unions, and tax policies that favor capital over labor income. The consequences of persistent inequality extend beyond mere financial disparity; research suggests it can undermine social cohesion, reduce intergenerational mobility, and even slow long-term economic growth by limiting access to education and opportunity for lower-income families. Addressing this issue requires a multifaceted approach, potentially including reforms to taxation, investment in public education, and policies that strengthen workers' bargaining power. However, there is considerable disagreement among policymakers and economists about which specific measures would be most effective without stifling economic dynamism.",
                "Climate change policy presents governments with a uniquely complex challenge, as it requires balancing immediate economic considerations against long-term environmental consequences that may not become fully apparent for decades. International cooperation is essential, given that greenhouse gas emissions in one country affect the entire planet, yet reaching consensus among nations with vastly different levels of development and historical responsibility for emissions has proven extraordinarily difficult. Developing countries often argue that wealthier nations, having benefited from decades of industrialization powered by fossil fuels, bear a greater responsibility to lead emission reductions and provide financial support for cleaner development pathways elsewhere. Meanwhile, domestic political pressures frequently complicate governments' ability to implement ambitious climate policies, as measures such as carbon taxes or restrictions on certain industries can face fierce opposition from affected businesses and workers. Navigating these competing interests while maintaining momentum toward meaningful emission reductions remains one of the most pressing challenges of our time.",
                "The nature of work is undergoing a profound transformation, driven by automation, artificial intelligence, and shifting economic structures. While technological progress has historically created new categories of employment even as it eliminated others, there is growing uncertainty about whether this pattern will hold in the face of increasingly sophisticated AI systems capable of performing cognitive tasks once thought to require uniquely human judgment. Some economists warn of significant disruption to labor markets, particularly for workers in routine or predictable roles, while others argue that human creativity, emotional intelligence, and complex problem-solving will remain difficult to automate, ensuring continued demand for human labor in redesigned forms. Regardless of which prediction proves more accurate, it seems clear that adaptability will become an increasingly valuable trait, and that education systems, social safety nets, and labor policies will need to evolve substantially to help workers navigate an increasingly uncertain and rapidly changing employment landscape.",
                "Cultural globalization, the process by which ideas, values, and cultural practices spread across national borders and become increasingly interconnected, has provoked considerable debate about its ultimate consequences for cultural diversity. Advocates contend that increased exposure to different cultures fosters greater mutual understanding and tolerance, while also providing economic opportunities through international trade in cultural products such as films, music, and literature. Critics, however, express concern that this process often results in cultural homogenization, whereby dominant cultures, particularly those originating from economically powerful nations, gradually overshadow and erode local traditions and languages. This phenomenon is sometimes described as a form of cultural imperialism, wherein smaller or less economically dominant cultures struggle to maintain their distinctiveness in the face of pervasive global media and commercial influence. Striking a balance between embracing the benefits of cultural exchange and preserving the rich diversity of local traditions remains an ongoing challenge for societies navigating an increasingly interconnected world.",
            ],
        ];

        // Đoạn văn tiếng Việt để luyện dịch chiều VI -> EN (3 đoạn/cấp)
        $passagesViEn = [
            'A1' => [
                "Gia đình tôi có bốn người: bố, mẹ, tôi và em gái. Bố tôi là bác sĩ. Mẹ tôi là giáo viên. Em gái tôi mới sáu tuổi và đang học lớp một. Chúng tôi sống trong một ngôi nhà nhỏ gần trường học. Mỗi buổi sáng, cả nhà cùng ăn sáng trước khi đi làm và đi học. Vào cuối tuần, chúng tôi thường đi công viên hoặc đến nhà ông bà chơi. Tôi rất yêu gia đình mình.",
                "Đây là phòng của tôi. Phòng không lớn nhưng rất gọn gàng. Có một cái giường, một cái bàn học và một cái tủ quần áo. Trên bàn học, tôi để sách vở và một cây đèn nhỏ. Tôi thích đọc sách trước khi đi ngủ. Trên tường, tôi treo vài bức tranh do chính tôi vẽ. Mỗi tối, tôi dọn dẹp phòng trước khi đi ngủ.",
                "Mỗi ngày tôi thức dậy lúc sáu giờ sáng. Sau khi đánh răng và rửa mặt, tôi ăn sáng cùng gia đình. Sau đó, tôi đi bộ đến trường vì trường gần nhà. Buổi sáng tôi học Toán và Tiếng Anh. Buổi trưa tôi ăn ở trường rồi nghỉ ngơi một chút. Buổi chiều tôi học thêm hai môn nữa rồi về nhà. Tôi làm bài tập vào buổi tối trước khi đi ngủ.",
            ],
            'A2' => [
                "Kỳ nghỉ hè năm ngoái, gia đình tôi đi biển ở Nha Trang trong một tuần. Thời tiết rất đẹp và biển rất trong xanh. Chúng tôi tắm biển mỗi buổi sáng và đi dạo trên bãi cát vào buổi tối. Tôi cũng học bơi ở đó với sự giúp đỡ của bố. Buổi tối, cả nhà thường đi ăn hải sản ở gần bãi biển. Đó là kỳ nghỉ vui nhất của tôi trong năm.",
                "Cuối tuần này tôi có nhiều việc phải làm. Sáng thứ Bảy tôi sẽ đi học thêm tiếng Anh. Buổi chiều tôi định đi mua sách với bạn thân. Chủ nhật là sinh nhật của mẹ tôi, nên cả nhà sẽ cùng nấu ăn và tổ chức một bữa tiệc nhỏ tại nhà. Tôi muốn mua cho mẹ một món quà thật đặc biệt. Tôi hy vọng cuối tuần này sẽ rất vui.",
                "Hôm qua tôi đi siêu thị cùng mẹ để mua đồ dùng cho năm học mới. Chúng tôi mua sách vở, bút và một chiếc cặp mới. Mẹ cũng mua một ít quần áo cho tôi vì quần áo cũ đã chật. Sau khi mua sắm xong, chúng tôi ăn trưa tại một nhà hàng nhỏ gần đó. Tôi rất thích chiếc cặp mới vì nó có màu tôi yêu thích.",
            ],
            'B1' => [
                "Văn hoá và truyền thống của mỗi quốc gia đều có những nét đặc trưng riêng. Ở Việt Nam, Tết Nguyên Đán là dịp lễ quan trọng nhất trong năm, khi mọi người sum họp cùng gia đình và tưởng nhớ tổ tiên. Ẩm thực cũng là một phần quan trọng của văn hoá. Mỗi vùng miền ở Việt Nam đều có những món ăn đặc sản riêng. Việc tìm hiểu văn hoá của các quốc gia khác giúp chúng ta trở nên cởi mở và hiểu biết hơn về thế giới xung quanh.",
                "Công nghệ đã thay đổi cách chúng ta sống và làm việc trong những năm gần đây. Điện thoại thông minh giúp con người liên lạc với nhau dễ dàng hơn, dù ở bất cứ đâu trên thế giới. Internet cũng mang lại nhiều cơ hội học tập và làm việc mới. Tuy nhiên, việc sử dụng công nghệ quá nhiều cũng gây ra một số vấn đề, như giảm thời gian giao tiếp trực tiếp giữa con người với nhau. Vì vậy, chúng ta cần sử dụng công nghệ một cách hợp lý và cân bằng.",
                "Vấn đề môi trường đang trở nên ngày càng nghiêm trọng trên toàn thế giới. Ô nhiễm không khí ở các thành phố lớn khiến sức khoẻ con người bị ảnh hưởng. Rác thải nhựa cũng đang gây hại nghiêm trọng cho các đại dương và sinh vật biển. Mỗi người đều có thể góp phần bảo vệ môi trường bằng những hành động nhỏ, như hạn chế sử dụng túi nilon, tiết kiệm điện nước và tham gia trồng cây xanh. Nếu tất cả cùng chung tay, chúng ta có thể tạo ra sự thay đổi tích cực cho hành tinh này.",
            ],
            'B2' => [
                "Mạng xã hội đã thay đổi cách con người giao tiếp và tiếp cận thông tin. Một mặt, nó giúp mọi người kết nối với bạn bè và người thân dễ dàng hơn, đồng thời tạo cơ hội cho các doanh nghiệp nhỏ quảng bá sản phẩm mà không cần chi phí lớn. Mặt khác, việc sử dụng mạng xã hội quá nhiều có thể gây ra căng thẳng, đặc biệt là ở giới trẻ khi so sánh cuộc sống của mình với hình ảnh được chỉnh sửa của người khác. Thông tin sai lệch cũng lan truyền rất nhanh trên các nền tảng này. Vì vậy, việc sử dụng mạng xã hội một cách có trách nhiệm là điều vô cùng cần thiết.",
                "Hệ thống giáo dục ở mỗi quốc gia phản ánh những giá trị văn hoá khác nhau. Một số nước tập trung vào việc ghi nhớ kiến thức và thi cử, khiến học sinh chịu nhiều áp lực nhưng đôi khi thiếu đi sự sáng tạo. Trong khi đó, một số hệ thống giáo dục khác chú trọng vào kỹ năng thực hành và tư duy độc lập, cho học sinh nhiều tự do hơn trong việc khám phá các lĩnh vực mình yêu thích. Không có mô hình nào là hoàn hảo, và nhiều chuyên gia giáo dục tin rằng cần kết hợp cả kiến thức học thuật lẫn kỹ năng mềm để chuẩn bị tốt hơn cho học sinh trước những thách thức trong tương lai.",
                "Việc cân bằng giữa công việc và cuộc sống cá nhân ngày càng trở nên khó khăn trong xã hội hiện đại, đặc biệt khi làm việc từ xa và kết nối liên tục qua điện thoại trở nên phổ biến. Nhiều nhân viên cảm thấy áp lực phải trả lời tin nhắn công việc ngay cả ngoài giờ làm, khiến ranh giới giữa công việc và cuộc sống cá nhân trở nên mờ nhạt. Điều này có thể dẫn đến kiệt sức và ảnh hưởng xấu đến sức khoẻ tinh thần. Một số công ty đã bắt đầu áp dụng chính sách giờ làm linh hoạt để giải quyết vấn đề này, nhưng mỗi cá nhân cũng cần tự đặt ra giới hạn cho riêng mình.",
            ],
            'C1' => [
                "Sự phát triển nhanh chóng của trí tuệ nhân tạo đã làm dấy lên nhiều tranh luận về vấn đề đạo đức, đặc biệt khi các hệ thống này ngày càng được tích hợp sâu vào các quy trình ra quyết định ảnh hưởng trực tiếp đến cuộc sống con người. Những người ủng hộ cho rằng trí tuệ nhân tạo có thể nâng cao hiệu quả và giảm thiểu định kiến của con người trong các lĩnh vực như tuyển dụng hay chẩn đoán y tế. Tuy nhiên, những người phản đối chỉ ra rằng các hệ thống này chỉ khách quan tương đương với dữ liệu mà chúng được huấn luyện, và những bất bình đẳng trong lịch sử có thể vô tình bị lặp lại hoặc thậm chí khuếch đại. Việc tìm ra sự cân bằng giữa thúc đẩy đổi mới và bảo vệ quyền lợi con người sẽ là thách thức trung tâm đối với các nhà hoạch định chính sách trong thời gian tới.",
                "Bất bình đẳng kinh tế đã trở thành một trong những vấn đề nổi bật nhất của thế kỷ hai mươi mốt, khi khoảng cách giữa nhóm giàu nhất và nghèo nhất trong xã hội ngày càng nới rộng dù nền kinh tế nói chung vẫn tăng trưởng. Các nhà kinh tế học cho rằng nguyên nhân đến từ nhiều yếu tố, bao gồm sự thay đổi công nghệ mang lại lợi ích không đồng đều cho lao động có kỹ năng cao, cũng như các chính sách thuế ưu tiên thu nhập từ vốn hơn thu nhập từ lao động. Hậu quả của bất bình đẳng kéo dài không chỉ dừng lại ở khía cạnh tài chính mà còn có thể làm suy yếu sự gắn kết xã hội và hạn chế cơ hội phát triển cho các thế hệ tương lai.",
                "Chính sách ứng phó với biến đổi khí hậu đặt ra một thách thức vô cùng phức tạp đối với các chính phủ, khi phải cân bằng giữa lợi ích kinh tế trước mắt và những hậu quả môi trường lâu dài có thể chưa bộc lộ rõ ràng trong nhiều thập kỷ tới. Hợp tác quốc tế là điều thiết yếu, bởi lượng khí thải nhà kính từ một quốc gia sẽ ảnh hưởng đến toàn bộ hành tinh, nhưng việc đạt được sự đồng thuận giữa các quốc gia có trình độ phát triển khác nhau lại vô cùng khó khăn. Nhiều nước đang phát triển cho rằng các nước giàu, vốn đã hưởng lợi từ nhiều thập kỷ công nghiệp hoá dựa trên nhiên liệu hoá thạch, cần có trách nhiệm lớn hơn trong việc dẫn đầu cắt giảm khí thải.",
            ],
        ];

        foreach ($passages as $level => $texts) {
            foreach ($texts as $text) {
                TranslationPassage::create([
                    'level' => $level,
                    'direction' => 'en_vi',
                    'source_text' => $text,
                ]);
            }
        }

        foreach ($passagesViEn as $level => $texts) {
            foreach ($texts as $text) {
                TranslationPassage::create([
                    'level' => $level,
                    'direction' => 'vi_en',
                    'source_text' => $text,
                ]);
            }
        }
    }
}
