<?php

namespace Database\Seeders;

use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

// Seed ~50 từ vựng mỗi cấp độ A1-C2 (mục 4). Dữ liệu mẫu, nghĩa tiếng Việt mang tính minh hoạ.
class VocabularySeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            'A1' => [
                ['cat', 'N.', '/kæt/', 'con mèo'],
                ['dog', 'N.', '/dɒg/', 'con chó'],
                ['house', 'N.', '/haʊs/', 'ngôi nhà'],
                ['water', 'N.', '/ˈwɔːtər/', 'nước'],
                ['book', 'N.', '/bʊk/', 'quyển sách'],
                ['table', 'N.', '/ˈteɪbl/', 'cái bàn'],
                ['chair', 'N.', '/tʃeər/', 'cái ghế'],
                ['apple', 'N.', '/ˈæpl/', 'quả táo'],
                ['red', 'Adj.', '/red/', 'màu đỏ'],
                ['blue', 'Adj.', '/bluː/', 'màu xanh dương'],
                ['big', 'Adj.', '/bɪg/', 'to lớn'],
                ['small', 'Adj.', '/smɔːl/', 'nhỏ'],
                ['happy', 'Adj.', '/ˈhæpi/', 'hạnh phúc'],
                ['sad', 'Adj.', '/sæd/', 'buồn'],
                ['run', 'V.', '/rʌn/', 'chạy'],
                ['walk', 'V.', '/wɔːk/', 'đi bộ'],
                ['eat', 'V.', '/iːt/', 'ăn'],
                ['drink', 'V.', '/drɪŋk/', 'uống'],
                ['sleep', 'V.', '/sliːp/', 'ngủ'],
                ['school', 'N.', '/skuːl/', 'trường học'],
                ['teacher', 'N.', '/ˈtiːtʃər/', 'giáo viên'],
                ['student', 'N.', '/ˈstjuːdənt/', 'học sinh'],
                ['friend', 'N.', '/frend/', 'bạn bè'],
                ['family', 'N.', '/ˈfæməli/', 'gia đình'],
                ['mother', 'N.', '/ˈmʌðər/', 'mẹ'],
                ['father', 'N.', '/ˈfɑːðər/', 'bố'],
                ['brother', 'N.', '/ˈbrʌðər/', 'anh/em trai'],
                ['sister', 'N.', '/ˈsɪstər/', 'chị/em gái'],
                ['day', 'N.', '/deɪ/', 'ngày'],
                ['night', 'N.', '/naɪt/', 'đêm'],
                ['morning', 'N.', '/ˈmɔːrnɪŋ/', 'buổi sáng'],
                ['evening', 'N.', '/ˈiːvnɪŋ/', 'buổi tối'],
                ['week', 'N.', '/wiːk/', 'tuần'],
                ['month', 'N.', '/mʌnθ/', 'tháng'],
                ['year', 'N.', '/jɪər/', 'năm'],
                ['color', 'N.', '/ˈkʌlər/', 'màu sắc'],
                ['food', 'N.', '/fuːd/', 'thức ăn'],
                ['car', 'N.', '/kɑːr/', 'xe hơi'],
                ['bus', 'N.', '/bʌs/', 'xe buýt'],
                ['train', 'N.', '/treɪn/', 'tàu hỏa'],
                ['city', 'N.', '/ˈsɪti/', 'thành phố'],
                ['country', 'N.', '/ˈkʌntri/', 'đất nước'],
                ['street', 'N.', '/striːt/', 'con phố'],
                ['door', 'N.', '/dɔːr/', 'cửa'],
                ['window', 'N.', '/ˈwɪndoʊ/', 'cửa sổ'],
                ['name', 'N.', '/neɪm/', 'tên'],
                ['good', 'Adj.', '/gʊd/', 'tốt'],
                ['new', 'Adj.', '/njuː/', 'mới'],
                ['old', 'Adj.', '/oʊld/', 'cũ/già'],
                ['love', 'V.', '/lʌv/', 'yêu'],
            ],
            'A2' => [
                ['weather', 'N.', '/ˈweðər/', 'thời tiết'],
                ['holiday', 'N.', '/ˈhɒlədeɪ/', 'kỳ nghỉ'],
                ['journey', 'N.', '/ˈdʒɜːrni/', 'chuyến đi'],
                ['airport', 'N.', '/ˈeərpɔːrt/', 'sân bay'],
                ['hotel', 'N.', '/hoʊˈtel/', 'khách sạn'],
                ['restaurant', 'N.', '/ˈrestrɒnt/', 'nhà hàng'],
                ['menu', 'N.', '/ˈmenjuː/', 'thực đơn'],
                ['waiter', 'N.', '/ˈweɪtər/', 'phục vụ bàn'],
                ['shopping', 'N.', '/ˈʃɒpɪŋ/', 'mua sắm'],
                ['market', 'N.', '/ˈmɑːrkɪt/', 'chợ'],
                ['price', 'N.', '/praɪs/', 'giá cả'],
                ['expensive', 'Adj.', '/ɪkˈspensɪv/', 'đắt'],
                ['cheap', 'Adj.', '/tʃiːp/', 'rẻ'],
                ['clothes', 'N.', '/kloʊðz/', 'quần áo'],
                ['shirt', 'N.', '/ʃɜːrt/', 'áo sơ mi'],
                ['shoes', 'N.', '/ʃuːz/', 'giày'],
                ['hospital', 'N.', '/ˈhɒspɪtl/', 'bệnh viện'],
                ['doctor', 'N.', '/ˈdɒktər/', 'bác sĩ'],
                ['medicine', 'N.', '/ˈmedsn/', 'thuốc'],
                ['sick', 'Adj.', '/sɪk/', 'ốm'],
                ['healthy', 'Adj.', '/ˈhelθi/', 'khỏe mạnh'],
                ['exercise', 'N.', '/ˈeksərsaɪz/', 'tập thể dục'],
                ['sport', 'N.', '/spɔːrt/', 'thể thao'],
                ['team', 'N.', '/tiːm/', 'đội'],
                ['win', 'V.', '/wɪn/', 'thắng'],
                ['lose', 'V.', '/luːz/', 'thua'],
                ['practice', 'V.', '/ˈpræktɪs/', 'luyện tập'],
                ['improve', 'V.', '/ɪmˈpruːv/', 'cải thiện'],
                ['decide', 'V.', '/dɪˈsaɪd/', 'quyết định'],
                ['remember', 'V.', '/rɪˈmembər/', 'nhớ'],
                ['forget', 'V.', '/fərˈget/', 'quên'],
                ['explain', 'V.', '/ɪkˈspleɪn/', 'giải thích'],
                ['understand', 'V.', '/ˌʌndərˈstænd/', 'hiểu'],
                ['borrow', 'V.', '/ˈbɒroʊ/', 'mượn'],
                ['lend', 'V.', '/lend/', 'cho mượn'],
                ['neighbor', 'N.', '/ˈneɪbər/', 'hàng xóm'],
                ['village', 'N.', '/ˈvɪlɪdʒ/', 'làng'],
                ['farmer', 'N.', '/ˈfɑːrmər/', 'nông dân'],
                ['factory', 'N.', '/ˈfæktri/', 'nhà máy'],
                ['company', 'N.', '/ˈkʌmpəni/', 'công ty'],
                ['manager', 'N.', '/ˈmænɪdʒər/', 'quản lý'],
                ['salary', 'N.', '/ˈsæləri/', 'lương'],
                ['interview', 'N.', '/ˈɪntərvjuː/', 'phỏng vấn'],
                ['experience', 'N.', '/ɪkˈspɪəriəns/', 'kinh nghiệm'],
                ['skill', 'N.', '/skɪl/', 'kỹ năng'],
                ['beginner', 'N.', '/bɪˈgɪnər/', 'người mới bắt đầu'],
                ['difficult', 'Adj.', '/ˈdɪfɪkəlt/', 'khó'],
                ['simple', 'Adj.', '/ˈsɪmpl/', 'đơn giản'],
                ['probably', 'Adv.', '/ˈprɒbəbli/', 'có lẽ'],
                ['suddenly', 'Adv.', '/ˈsʌdənli/', 'đột nhiên'],
            ],
            'B1' => [
                ['environment', 'N.', '/ɪnˈvaɪrənmənt/', 'môi trường'],
                ['pollution', 'N.', '/pəˈluːʃn/', 'ô nhiễm'],
                ['climate', 'N.', '/ˈklaɪmət/', 'khí hậu'],
                ['resource', 'N.', '/rɪˈsɔːrs/', 'tài nguyên'],
                ['energy', 'N.', '/ˈenərdʒi/', 'năng lượng'],
                ['renewable', 'Adj.', '/rɪˈnjuːəbl/', 'có thể tái tạo'],
                ['society', 'N.', '/səˈsaɪəti/', 'xã hội'],
                ['culture', 'N.', '/ˈkʌltʃər/', 'văn hóa'],
                ['tradition', 'N.', '/trəˈdɪʃn/', 'truyền thống'],
                ['custom', 'N.', '/ˈkʌstəm/', 'phong tục'],
                ['government', 'N.', '/ˈgʌvərnmənt/', 'chính phủ'],
                ['economy', 'N.', '/ɪˈkɒnəmi/', 'kinh tế'],
                ['industry', 'N.', '/ˈɪndəstri/', 'ngành công nghiệp'],
                ['technology', 'N.', '/tekˈnɒlədʒi/', 'công nghệ'],
                ['develop', 'V.', '/dɪˈveləp/', 'phát triển'],
                ['achieve', 'V.', '/əˈtʃiːv/', 'đạt được'],
                ['challenge', 'N.', '/ˈtʃælɪndʒ/', 'thử thách'],
                ['opportunity', 'N.', '/ˌɒpərˈtjuːnəti/', 'cơ hội'],
                ['relationship', 'N.', '/rɪˈleɪʃnʃɪp/', 'mối quan hệ'],
                ['communicate', 'V.', '/kəˈmjuːnɪkeɪt/', 'giao tiếp'],
                ['opinion', 'N.', '/əˈpɪnjən/', 'ý kiến'],
                ['argument', 'N.', '/ˈɑːrgjumənt/', 'lập luận/tranh cãi'],
                ['persuade', 'V.', '/pərˈsweɪd/', 'thuyết phục'],
                ['convince', 'V.', '/kənˈvɪns/', 'thuyết phục'],
                ['suggest', 'V.', '/səˈdʒest/', 'đề nghị'],
                ['recommend', 'V.', '/ˌrekəˈmend/', 'giới thiệu/đề xuất'],
                ['reduce', 'V.', '/rɪˈdjuːs/', 'giảm'],
                ['increase', 'V.', '/ɪnˈkriːs/', 'tăng'],
                ['affect', 'V.', '/əˈfekt/', 'ảnh hưởng'],
                ['benefit', 'N.', '/ˈbenɪfɪt/', 'lợi ích'],
                ['disadvantage', 'N.', '/ˌdɪsədˈvɑːntɪdʒ/', 'bất lợi'],
                ['advantage', 'N.', '/ədˈvɑːntɪdʒ/', 'lợi thế'],
                ['responsible', 'Adj.', '/rɪˈspɒnsəbl/', 'có trách nhiệm'],
                ['independent', 'Adj.', '/ˌɪndɪˈpendənt/', 'độc lập'],
                ['confident', 'Adj.', '/ˈkɒnfɪdənt/', 'tự tin'],
                ['anxious', 'Adj.', '/ˈæŋkʃəs/', 'lo lắng'],
                ['curious', 'Adj.', '/ˈkjʊəriəs/', 'tò mò'],
                ['generous', 'Adj.', '/ˈdʒenərəs/', 'hào phóng'],
                ['stubborn', 'Adj.', '/ˈstʌbərn/', 'bướng bỉnh'],
                ['ambitious', 'Adj.', '/æmˈbɪʃəs/', 'tham vọng'],
                ['eventually', 'Adv.', '/ɪˈventʃuəli/', 'cuối cùng'],
                ['gradually', 'Adv.', '/ˈgrædʒuəli/', 'dần dần'],
                ['immediately', 'Adv.', '/ɪˈmiːdiətli/', 'ngay lập tức'],
                ['approximately', 'Adv.', '/əˈprɒksɪmətli/', 'xấp xỉ'],
                ['despite', 'Prep.', '/dɪˈspaɪt/', 'mặc dù'],
                ['although', 'Conj.', '/ɔːlˈðoʊ/', 'mặc dù'],
                ['therefore', 'Adv.', '/ˈðeərfɔːr/', 'vì vậy'],
                ['however', 'Adv.', '/haʊˈevər/', 'tuy nhiên'],
                ['moreover', 'Adv.', '/mɔːrˈoʊvər/', 'hơn nữa'],
                ['nevertheless', 'Adv.', '/ˌnevərðəˈles/', 'tuy nhiên'],
            ],
            'B2' => [
                ['sustainability', 'N.', '/səˌsteɪnəˈbɪləti/', 'tính bền vững'],
                ['globalization', 'N.', '/ˌgloʊbəlaɪˈzeɪʃn/', 'toàn cầu hóa'],
                ['innovation', 'N.', '/ˌɪnəˈveɪʃn/', 'sự đổi mới'],
                ['entrepreneur', 'N.', '/ˌɒntrəprəˈnɜːr/', 'doanh nhân'],
                ['investment', 'N.', '/ɪnˈvestmənt/', 'đầu tư'],
                ['inflation', 'N.', '/ɪnˈfleɪʃn/', 'lạm phát'],
                ['recession', 'N.', '/rɪˈseʃn/', 'suy thoái'],
                ['regulation', 'N.', '/ˌregjuˈleɪʃn/', 'quy định'],
                ['legislation', 'N.', '/ˌledʒɪsˈleɪʃn/', 'luật pháp'],
                ['controversial', 'Adj.', '/ˌkɒntrəˈvɜːrʃl/', 'gây tranh cãi'],
                ['inevitable', 'Adj.', '/ɪnˈevɪtəbl/', 'không thể tránh khỏi'],
                ['significant', 'Adj.', '/sɪgˈnɪfɪkənt/', 'đáng kể'],
                ['substantial', 'Adj.', '/səbˈstænʃl/', 'đáng kể/lớn'],
                ['comprehensive', 'Adj.', '/ˌkɒmprɪˈhensɪv/', 'toàn diện'],
                ['sophisticated', 'Adj.', '/səˈfɪstɪkeɪtɪd/', 'tinh vi'],
                ['versatile', 'Adj.', '/ˈvɜːrsətaɪl/', 'đa năng'],
                ['perceive', 'V.', '/pərˈsiːv/', 'nhận thức'],
                ['acknowledge', 'V.', '/əkˈnɒlɪdʒ/', 'thừa nhận'],
                ['anticipate', 'V.', '/ænˈtɪsɪpeɪt/', 'dự đoán'],
                ['undermine', 'V.', '/ˌʌndərˈmaɪn/', 'làm suy yếu'],
                ['enhance', 'V.', '/ɪnˈhæns/', 'nâng cao'],
                ['facilitate', 'V.', '/fəˈsɪlɪteɪt/', 'tạo điều kiện'],
                ['implement', 'V.', '/ˈɪmplɪment/', 'thực hiện'],
                ['establish', 'V.', '/ɪˈstæblɪʃ/', 'thiết lập'],
                ['eliminate', 'V.', '/ɪˈlɪmɪneɪt/', 'loại bỏ'],
                ['exaggerate', 'V.', '/ɪgˈzædʒəreɪt/', 'phóng đại'],
                ['justify', 'V.', '/ˈdʒʌstɪfaɪ/', 'biện minh'],
                ['compensate', 'V.', '/ˈkɒmpenseɪt/', 'bồi thường'],
                ['accumulate', 'V.', '/əˈkjuːmjəleɪt/', 'tích lũy'],
                ['allocate', 'V.', '/ˈæləkeɪt/', 'phân bổ'],
                ['consequence', 'N.', '/ˈkɒnsɪkwəns/', 'hậu quả'],
                ['phenomenon', 'N.', '/fəˈnɒmɪnən/', 'hiện tượng'],
                ['hypothesis', 'N.', '/haɪˈpɒθəsɪs/', 'giả thuyết'],
                ['methodology', 'N.', '/ˌmeθəˈdɒlədʒi/', 'phương pháp luận'],
                ['criteria', 'N.', '/kraɪˈtɪəriə/', 'tiêu chí'],
                ['perspective', 'N.', '/pərˈspektɪv/', 'quan điểm'],
                ['dilemma', 'N.', '/dɪˈlemə/', 'tình huống khó xử'],
                ['paradox', 'N.', '/ˈpærədɒks/', 'nghịch lý'],
                ['bias', 'N.', '/ˈbaɪəs/', 'thiên kiến'],
                ['integrity', 'N.', '/ɪnˈtegrəti/', 'sự chính trực'],
                ['autonomy', 'N.', '/ɔːˈtɒnəmi/', 'quyền tự chủ'],
                ['diversity', 'N.', '/daɪˈvɜːrsəti/', 'sự đa dạng'],
                ['equality', 'N.', '/iˈkwɒləti/', 'sự bình đẳng'],
                ['discrimination', 'N.', '/dɪˌskrɪmɪˈneɪʃn/', 'sự phân biệt đối xử'],
                ['empathy', 'N.', '/ˈempəθi/', 'sự đồng cảm'],
                ['resilience', 'N.', '/rɪˈzɪliəns/', 'khả năng phục hồi'],
                ['arguably', 'Adv.', '/ˈɑːrgjuəbli/', 'có thể nói là'],
                ['inherently', 'Adv.', '/ɪnˈherəntli/', 'vốn dĩ'],
                ['predominantly', 'Adv.', '/prɪˈdɒmɪnəntli/', 'chủ yếu'],
                ['nonetheless', 'Adv.', '/ˌnʌnðəˈles/', 'tuy nhiên'],
            ],
            'C1' => [
                ['ubiquitous', 'Adj.', '/juːˈbɪkwɪtəs/', 'có mặt khắp nơi'],
                ['ambiguous', 'Adj.', '/æmˈbɪgjuəs/', 'mơ hồ'],
                ['meticulous', 'Adj.', '/məˈtɪkjələs/', 'tỉ mỉ'],
                ['pragmatic', 'Adj.', '/prægˈmætɪk/', 'thực dụng'],
                ['plausible', 'Adj.', '/ˈplɔːzəbl/', 'hợp lý/có thể tin được'],
                ['arbitrary', 'Adj.', '/ˈɑːrbɪtrəri/', 'tùy tiện'],
                ['coherent', 'Adj.', '/koʊˈhɪərənt/', 'mạch lạc'],
                ['redundant', 'Adj.', '/rɪˈdʌndənt/', 'dư thừa'],
                ['viable', 'Adj.', '/ˈvaɪəbl/', 'khả thi'],
                ['tenuous', 'Adj.', '/ˈtenjuəs/', 'mong manh'],
                ['eloquent', 'Adj.', '/ˈeləkwənt/', 'hùng biện'],
                ['candid', 'Adj.', '/ˈkændɪd/', 'thẳng thắn'],
                ['astute', 'Adj.', '/əˈstjuːt/', 'tinh tường'],
                ['profound', 'Adj.', '/prəˈfaʊnd/', 'sâu sắc'],
                ['subtle', 'Adj.', '/ˈsʌtl/', 'tinh tế'],
                ['elaborate', 'V.', '/ɪˈlæbəreɪt/', 'trình bày chi tiết'],
                ['corroborate', 'V.', '/kəˈrɒbəreɪt/', 'xác nhận/củng cố'],
                ['substantiate', 'V.', '/səbˈstænʃieɪt/', 'chứng minh'],
                ['reconcile', 'V.', '/ˈrekənsaɪl/', 'hòa giải'],
                ['mitigate', 'V.', '/ˈmɪtɪgeɪt/', 'giảm nhẹ'],
                ['exacerbate', 'V.', '/ɪgˈzæsərbeɪt/', 'làm trầm trọng thêm'],
                ['alleviate', 'V.', '/əˈliːvieɪt/', 'làm giảm bớt'],
                ['circumvent', 'V.', '/ˌsɜːrkəmˈvent/', 'lách qua'],
                ['relinquish', 'V.', '/rɪˈlɪŋkwɪʃ/', 'từ bỏ'],
                ['articulate', 'V.', '/ɑːrˈtɪkjuleɪt/', 'diễn đạt rõ ràng'],
                ['contemplate', 'V.', '/ˈkɒntəmpleɪt/', 'suy ngẫm'],
                ['discern', 'V.', '/dɪˈsɜːrn/', 'nhận ra'],
                ['infer', 'V.', '/ɪnˈfɜːr/', 'suy luận'],
                ['presume', 'V.', '/prɪˈzjuːm/', 'cho là/giả định'],
                ['reiterate', 'V.', '/riˈɪtəreɪt/', 'nhắc lại'],
                ['paradigm', 'N.', '/ˈpærədaɪm/', 'hệ hình/mô hình'],
                ['dichotomy', 'N.', '/daɪˈkɒtəmi/', 'sự phân đôi'],
                ['connotation', 'N.', '/ˌkɒnəˈteɪʃn/', 'hàm ý'],
                ['discrepancy', 'N.', '/dɪˈskrepənsi/', 'sự khác biệt/mâu thuẫn'],
                ['anomaly', 'N.', '/əˈnɒməli/', 'điều bất thường'],
                ['proponent', 'N.', '/prəˈpoʊnənt/', 'người ủng hộ'],
                ['adversary', 'N.', '/ˈædvərsəri/', 'đối thủ'],
                ['deterrent', 'N.', '/dɪˈtɜːrənt/', 'biện pháp răn đe'],
                ['incentive', 'N.', '/ɪnˈsentɪv/', 'động lực/khuyến khích'],
                ['repercussion', 'N.', '/ˌriːpərˈkʌʃn/', 'hậu quả'],
                ['legacy', 'N.', '/ˈlegəsi/', 'di sản'],
                ['tenet', 'N.', '/ˈtenɪt/', 'nguyên tắc/tín điều'],
                ['testament', 'N.', '/ˈtestəmənt/', 'minh chứng'],
                ['conundrum', 'N.', '/kəˈnʌndrəm/', 'vấn đề nan giải'],
                ['inadvertently', 'Adv.', '/ˌɪnədˈvɜːrtəntli/', 'vô tình'],
                ['ostensibly', 'Adv.', '/ɒˈstensəbli/', 'có vẻ như'],
                ['unequivocally', 'Adv.', '/ˌʌnɪˈkwɪvəkəli/', 'rõ ràng/dứt khoát'],
                ['albeit', 'Conj.', '/ɔːlˈbiːɪt/', 'mặc dù'],
                ['notwithstanding', 'Prep.', '/ˌnɒtwɪθˈstændɪŋ/', 'mặc dù'],
                ['henceforth', 'Adv.', '/ˌhensˈfɔːrθ/', 'từ nay trở đi'],
            ],
            'C2' => [
                ['perspicacious', 'Adj.', '/ˌpɜːrspɪˈkeɪʃəs/', 'sắc sảo/tinh tường'],
                ['sagacious', 'Adj.', '/səˈgeɪʃəs/', 'khôn ngoan'],
                ['quintessential', 'Adj.', '/ˌkwɪntɪˈsenʃl/', 'điển hình nhất'],
                ['ephemeral', 'Adj.', '/ɪˈfemərəl/', 'phù du/ngắn ngủi'],
                ['esoteric', 'Adj.', '/ˌesəˈterɪk/', 'bí truyền/khó hiểu'],
                ['idiosyncratic', 'Adj.', '/ˌɪdiəsɪŋˈkrætɪk/', 'đặc trưng riêng'],
                ['surreptitious', 'Adj.', '/ˌsʌrəpˈtɪʃəs/', 'lén lút'],
                ['magnanimous', 'Adj.', '/mægˈnænɪməs/', 'hào hiệp'],
                ['gregarious', 'Adj.', '/grɪˈgeəriəs/', 'thích giao du'],
                ['fastidious', 'Adj.', '/fæˈstɪdiəs/', 'khó tính/kỹ tính'],
                ['obsequious', 'Adj.', '/əbˈsiːkwiəs/', 'xu nịnh'],
                ['vindictive', 'Adj.', '/vɪnˈdɪktɪv/', 'hay thù hằn'],
                ['ostentatious', 'Adj.', '/ˌɒstenˈteɪʃəs/', 'phô trương'],
                ['laconic', 'Adj.', '/ləˈkɒnɪk/', 'ngắn gọn/kiệm lời'],
                ['verbose', 'Adj.', '/vɜːrˈboʊs/', 'dài dòng'],
                ['equivocate', 'V.', '/ɪˈkwɪvəkeɪt/', 'nói nước đôi'],
                ['extrapolate', 'V.', '/ɪkˈstræpəleɪt/', 'suy rộng ra'],
                ['vacillate', 'V.', '/ˈvæsɪleɪt/', 'dao động/lưỡng lự'],
                ['proliferate', 'V.', '/prəˈlɪfəreɪt/', 'sinh sôi/lan rộng'],
                ['capitulate', 'V.', '/kəˈpɪtʃuleɪt/', 'đầu hàng'],
                ['exculpate', 'V.', '/ˈekskʌlpeɪt/', 'minh oan'],
                ['denigrate', 'V.', '/ˈdenɪgreɪt/', 'hạ thấp/bôi nhọ'],
                ['placate', 'V.', '/pləˈkeɪt/', 'xoa dịu'],
                ['galvanize', 'V.', '/ˈgælvənaɪz/', 'thúc đẩy/kích động'],
                ['exonerate', 'V.', '/ɪgˈzɒnəreɪt/', 'minh oan/miễn tội'],
                ['conflate', 'V.', '/kənˈfleɪt/', 'hợp nhất/lẫn lộn'],
                ['juxtapose', 'V.', '/ˈdʒʌkstəpoʊz/', 'đặt cạnh nhau để so sánh'],
                ['obfuscate', 'V.', '/ˈɒbfʌskeɪt/', 'làm mù mờ'],
                ['usurp', 'V.', '/juˈzɜːrp/', 'chiếm đoạt'],
                ['vindicate', 'V.', '/ˈvɪndɪkeɪt/', 'minh oan/chứng minh đúng'],
                ['cacophony', 'N.', '/kəˈkɒfəni/', 'âm thanh hỗn độn'],
                ['juxtaposition', 'N.', '/ˌdʒʌkstəpəˈzɪʃn/', 'sự đặt cạnh nhau'],
                ['schism', 'N.', '/ˈsɪzəm/', 'sự chia rẽ'],
                ['hegemony', 'N.', '/hɪˈdʒeməni/', 'bá quyền'],
                ['zeitgeist', 'N.', '/ˈzaɪtgaɪst/', 'tinh thần thời đại'],
                ['epiphany', 'N.', '/ɪˈpɪfəni/', 'khoảnh khắc giác ngộ'],
                ['panacea', 'N.', '/ˌpænəˈsiːə/', 'thuốc chữa bách bệnh'],
                ['quandary', 'N.', '/ˈkwɒndəri/', 'tình thế khó xử'],
                ['exigency', 'N.', '/ˈeksɪdʒənsi/', 'tình thế cấp bách'],
                ['proclivity', 'N.', '/prəˈklɪvəti/', 'khuynh hướng'],
                ['vicissitude', 'N.', '/vɪˈsɪsɪtjuːd/', 'sự thăng trầm'],
                ['nomenclature', 'N.', '/noʊˈmenklətʃər/', 'hệ thống danh pháp'],
                ['verisimilitude', 'N.', '/ˌverɪsɪˈmɪlɪtjuːd/', 'tính chân thực'],
                ['solipsism', 'N.', '/ˈsɒlɪpsɪzəm/', 'chủ nghĩa duy ngã'],
                ['surreptitiously', 'Adv.', '/ˌsʌrəpˈtɪʃəsli/', 'một cách lén lút'],
                ['unabashedly', 'Adv.', '/ˌʌnəˈbæʃɪdli/', 'không hề xấu hổ'],
                ['inexorably', 'Adv.', '/ɪnˈeksərəbli/', 'không thể ngăn cản'],
                ['ostensible', 'Adj.', '/ɒˈstensəbl/', 'bề ngoài/có vẻ như'],
                ['per se', 'Adv.', '/pɜːr ˈseɪ/', 'tự bản thân nó'],
                ['axiomatic', 'Adj.', '/ˌæksiəˈmætɪk/', 'hiển nhiên'],
            ],
        ];

        foreach ($data as $level => $words) {
            foreach ($words as [$word, $pos, $ipa, $meaning]) {
                Vocabulary::create([
                    'level' => $level,
                    'word' => $word,
                    'part_of_speech' => $pos,
                    'ipa' => $ipa,
                    'meaning_vi' => $meaning,
                ]);
            }
        }
    }
}
